version: '3.9'
services:
  st-angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    container_name: st-angular
    volumes:
       - .:/usr/src/simple-twitch
    command: [npm, start]